#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    ar.sort()
    a=[]
    for i in range(len(ar)):
        if ar[i] not in a:
            a.append(ar[i])
    b=[]
    for j in range(len(a)):
        ab=ar.count(a[j])
        b.append(ab)
    c=[]
    for i in range(len(b)):
        c.append(int(b[i]/2))
    return(sum(c))    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
